assignCountryNames <- function(data) {
data$country <- ""
data$country <- ifelse(data$cowcode == 700 , 'Afghanistan'  , data$country)
data$country <- ifelse(data$cowcode == 339 , 'Albania'  , data$country)
data$country <- ifelse(data$cowcode == 615 , 'Algeria'  , data$country)
data$country <- ifelse(data$cowcode == 232 , 'Andorra'  , data$country)
data$country <- ifelse(data$cowcode == 540 , 'Angola'  , data$country)
data$country <- ifelse(data$cowcode == 58 , 'Antigua & Barbuda' , data$country)
data$country <- ifelse(data$cowcode == 160 , 'Argentina'  , data$country)
data$country <- ifelse(data$cowcode == 371 , 'Armenia' , data$country)
data$country <- ifelse(data$cowcode == 900 , 'Australia' , data$country)
data$country <- ifelse(data$cowcode == 305 , 'Austria'  , data$country)
data$country <- ifelse(data$cowcode == 300 , 'Austria-Hungary'  , data$country)
data$country <- ifelse(data$cowcode == 3 ,'Azerbaijan' , data$country)
data$country <- ifelse(data$cowcode == 267 , 'Baden'  , data$country)
data$country <- ifelse(data$cowcode == 31 , 'Bahamas' , data$country)
data$country <- ifelse(data$cowcode == 692 , 'Bahrain' , data$country)
data$country <- ifelse(data$cowcode == 771 , 'Bangladesh'  , data$country)
data$country <- ifelse(data$cowcode == 53 , 'Barbados' , data$country)
data$country <- ifelse(data$cowcode == 245 , 'Bavaria'  , data$country)
data$country <- ifelse(data$cowcode == 370 , 'Belarus' , data$country)
data$country <- ifelse(data$cowcode == 211 , 'Belgium'  , data$country)
data$country <- ifelse(data$cowcode == 80 , 'Belize'  , data$country)
data$country <- ifelse(data$cowcode == 434 , 'Benin'  , data$country)
data$country <- ifelse(data$cowcode == 760 , 'Bhutan' , data$country)
data$country <- ifelse(data$cowcode == 145 , 'Bolivia'  , data$country)
data$country <- ifelse(data$cowcode == 346 , 'Bosnia and Herzegovina' , data$country)
data$country <- ifelse(data$cowcode == 571 , 'Botswana'  , data$country)
data$country <- ifelse(data$cowcode == 140 , 'Brazil'  , data$country)
data$country <- ifelse(data$cowcode == 835 , 'Brunei' , data$country)
data$country <- ifelse(data$cowcode == 355 , 'Bulgaria'  , data$country)
data$country <- ifelse(data$cowcode == 439 , 'Burkina Faso' , data$country)
data$country <- ifelse(data$cowcode == 516 , 'Burundi'  , data$country)
data$country <- ifelse(data$cowcode == 811 , 'Cambodia' , data$country)
data$country <- ifelse(data$cowcode == 471 , 'Cameroon'  , data$country)
data$country <- ifelse(data$cowcode == 20 , 'Canada'  , data$country)
data$country <- ifelse(data$cowcode == 402 , 'Cape Verde' , data$country)
data$country <- ifelse(data$cowcode == 482 , 'Central African Republic' , data$country)
data$country <- ifelse(data$cowcode == 483 , 'Chad'  , data$country)
data$country <- ifelse(data$cowcode == 155 , 'Chile'  , data$country)
data$country <- ifelse(data$cowcode == 710 , 'China' , data$country)
data$country <- ifelse(data$cowcode == 100 , 'Colombia' , data$country)
data$country <- ifelse(data$cowcode == 581 , 'Comoros' , data$country)
data$country <- ifelse(data$cowcode == 484 , 'Congo, Rep.' , data$country)
data$country <- ifelse(data$cowcode == 94 , 'Costa Rica' , data$country)
data$country <- ifelse(data$cowcode == 344 , 'Croatia' , data$country)
data$country <- ifelse(data$cowcode == 40 , 'Cuba' , data$country)
data$country <- ifelse(data$cowcode == 352 , 'Cyprus' , data$country)
data$country <- ifelse(data$cowcode == 316 , 'Czech Republic' , data$country)
data$country <- ifelse(data$cowcode == 315 , 'Czechoslovakia'  , data$country)
data$country <- ifelse(data$cowcode == 390 , 'Denmark' , data$country)
data$country <- ifelse(data$cowcode == 522 , 'Djibouti'  , data$country)
data$country <- ifelse(data$cowcode == 54 , 'Dominica' , data$country)
data$country <- ifelse(data$cowcode == 42 , 'Dominican Republic'  , data$country)
data$country <- ifelse(data$cowcode == 860 , 'East Timor'  , data$country)
data$country <- ifelse(data$cowcode == 130 , 'Ecuador'  , data$country)
data$country <- ifelse(data$cowcode == 651 , 'Egypt' , data$country)
data$country <- ifelse(data$cowcode == 92 , 'El Salvador'  , data$country)
data$country <- ifelse(data$cowcode == 411 , 'Equatorial Guinea' , data$country)
data$country <- ifelse(data$cowcode == 531 , 'Eritrea' , data$country)
data$country <- ifelse(data$cowcode == 366 , 'Estonia' , data$country)
data$country <- ifelse(data$cowcode == 530 , 'Ethiopia'  , data$country)
data$country <- ifelse(data$cowcode == 987 , 'Micronesia' , data$country)
data$country <- ifelse(data$cowcode == 950 , 'Fiji'  , data$country)
data$country <- ifelse(data$cowcode == 375 , 'Finland'  , data$country)
data$country <- ifelse(data$cowcode == 220 , 'France'  , data$country)
data$country <- ifelse(data$cowcode == 481 , 'Gabon'  , data$country)
data$country <- ifelse(data$cowcode == 420 , 'Gambia' , data$country)
data$country <- ifelse(data$cowcode == 372 , 'Georgia' , data$country)
data$country <- ifelse(data$cowcode == 265 , 'East Germany'  , data$country)
data$country <- ifelse(data$cowcode == 260 , 'West Germany' , data$country)
data$country <- ifelse(data$cowcode == 255 , 'Germany' , data$country)
data$country <- ifelse(data$cowcode == 452 , 'Ghana'  , data$country)
data$country <- ifelse(data$cowcode == 350 , 'Greece'  , data$country)
data$country <- ifelse(data$cowcode == 55 , 'Grenada'  , data$country)
data$country <- ifelse(data$cowcode == 90 , 'Guatemala'  , data$country)
data$country <- ifelse(data$cowcode == 438 , 'Guinea'  , data$country)
data$country <- ifelse(data$cowcode == 404 , 'Guinea-Bissau' , data$country)
data$country <- ifelse(data$cowcode == 110 , 'Guyana'  , data$country)
data$country <- ifelse(data$cowcode == 41 , 'Haiti'  , data$country)
data$country <- ifelse(data$cowcode == 240 , 'Hanover' , data$country)
data$country <- ifelse(data$cowcode == 273 , 'Hesse Electoral' , data$country)
data$country <- ifelse(data$cowcode == 275 , 'Hesse Grand Ducal' , data$country)
data$country <- ifelse(data$cowcode == 91 , 'Honduras' , data$country)
data$country <- ifelse(data$cowcode == 310 , 'Hungary'  , data$country)
data$country <- ifelse(data$cowcode == 395 , 'Iceland'  , data$country)
data$country <- ifelse(data$cowcode == 750 , 'India'  , data$country)
data$country <- ifelse(data$cowcode == 850 , 'Indonesia' , data$country)
data$country <- ifelse(data$cowcode == 630 , 'Iran' , data$country)
data$country <- ifelse(data$cowcode == 645 , 'Iraq'  , data$country)
data$country <- ifelse(data$cowcode == 205 , 'Ireland'  , data$country)
data$country <- ifelse(data$cowcode == 666 , 'Israel'  , data$country)
data$country <- ifelse(data$cowcode == 325 , 'Italy'  , data$country)
data$country <- ifelse(data$cowcode == 437 , 'Ivory Coast' , data$country)
data$country <- ifelse(data$cowcode == 51 , 'Jamaica'  , data$country)
data$country <- ifelse(data$cowcode == 740 , 'Japan'  , data$country)
data$country <- ifelse(data$cowcode == 663 , 'Jordan'  , data$country)
data$country <- ifelse(data$cowcode == 705 , 'Kazakhstan' , data$country)
data$country <- ifelse(data$cowcode == 501 , 'Kenya' , data$country)
data$country <- ifelse(data$cowcode == 946 , 'Kiribati' , data$country)
data$country <- ifelse(data$cowcode == 730 , 'Korea' , data$country)
data$country <- ifelse(data$cowcode == 347 , 'Kosovo' , data$country)
data$country <- ifelse(data$cowcode == 690 , 'Kuwait' , data$country)
data$country <- ifelse(data$cowcode == 703 , 'Kyrgyzstan' , data$country)
data$country <- ifelse(data$cowcode == 812 , 'Lao PDR' , data$country)
data$country <- ifelse(data$cowcode == 367 , 'Latvia' , data$country)
data$country <- ifelse(data$cowcode == 660 , 'Lebanon' , data$country)
data$country <- ifelse(data$cowcode == 570 , 'Lesotho'  , data$country)
data$country <- ifelse(data$cowcode == 450 , 'Liberia'  , data$country)
data$country <- ifelse(data$cowcode == 620 , 'Libya' , data$country)
data$country <- ifelse(data$cowcode == 223 , 'Liechtenstein' , data$country)
data$country <- ifelse(data$cowcode == 368 , 'Lithuania' , data$country)
data$country <- ifelse(data$cowcode == 212 , 'Luxembourg'  , data$country)
data$country <- ifelse(data$cowcode == 343 , 'Macedonia' , data$country)
data$country <- ifelse(data$cowcode == 580 , 'Madagascar'  , data$country)
data$country <- ifelse(data$cowcode == 553 , 'Malawi'  , data$country)
data$country <- ifelse(data$cowcode == 820 , 'Malaysia'  , data$country)
data$country <- ifelse(data$cowcode == 781 , 'Maldives' , data$country)
data$country <- ifelse(data$cowcode == 432 , 'Mali'  , data$country)
data$country <- ifelse(data$cowcode == 338 , 'Malta'  , data$country)
data$country <- ifelse(data$cowcode == 983 , 'Marshall Islands' , data$country)
data$country <- ifelse(data$cowcode == 435 , 'Mauritania' , data$country)
data$country <- ifelse(data$cowcode == 590 , 'Mauritius'  , data$country)
data$country <- ifelse(data$cowcode == 280 , 'Mecklenburg Schwerin' , data$country)
data$country <- ifelse(data$cowcode == 70 , 'Mexico'  , data$country)
data$country <- ifelse(data$cowcode == 332 , 'Modena' , data$country)
data$country <- ifelse(data$cowcode == 359 , 'Moldova' , data$country)
data$country <- ifelse(data$cowcode == 221 , 'Monaco' , data$country)
data$country <- ifelse(data$cowcode == 712 , 'Mongolia'  , data$country)
data$country <- ifelse(data$cowcode == 341 , 'Montenegro' , data$country)
data$country <- ifelse(data$cowcode == 600 , 'Morocco'  , data$country)
data$country <- ifelse(data$cowcode == 541 , 'Mozambique'  , data$country)
data$country <- ifelse(data$cowcode == 775 , 'Myanmar'  , data$country)
data$country <- ifelse(data$cowcode == 565 , 'Namibia' , data$country)
data$country <- ifelse(data$cowcode == 970 , 'Nauru' , data$country)
data$country <- ifelse(data$cowcode == 790 , 'Nepal'  , data$country)
data$country <- ifelse(data$cowcode == 210 , 'Netherlands'  , data$country)
data$country <- ifelse(data$cowcode == 920 , 'New Zealand'  , data$country)
data$country <- ifelse(data$cowcode == 93 , 'Nicaragua'  , data$country)
data$country <- ifelse(data$cowcode == 436 , 'Niger'  , data$country)
data$country <- ifelse(data$cowcode == 475 , 'Nigeria'  , data$country)
data$country <- ifelse(data$cowcode == 731 , 'Korea, North ' , data$country)
data$country <- ifelse(data$cowcode == 385 , 'Norway'  , data$country)
data$country <- ifelse(data$cowcode == 698 , 'Oman' , data$country)
data$country <- ifelse(data$cowcode == 770 , 'Pakistan'  , data$country)
data$country <- ifelse(data$cowcode == 986 , 'Palau' , data$country)
data$country <- ifelse(data$cowcode == 95 , 'Panama'  , data$country)
data$country <- ifelse(data$cowcode == 327 , 'Papal States' , data$country)
data$country <- ifelse(data$cowcode == 910 , 'Papua New Guinea'  , data$country)
data$country <- ifelse(data$cowcode == 150 , 'Paraguay'  , data$country)
data$country <- ifelse(data$cowcode == 335 , 'Parma' , data$country)
data$country <- ifelse(data$cowcode == 135 , 'Peru'  , data$country)
data$country <- ifelse(data$cowcode == 840 , 'Philippines'  , data$country)
data$country <- ifelse(data$cowcode == 290 , 'Poland'  , data$country)
data$country <- ifelse(data$cowcode == 235 , 'Portugal'  , data$country)
data$country <- ifelse(data$cowcode == 694 , 'Qatar' , data$country)
data$country <- ifelse(data$cowcode == 694 , 'Qatar' , data$country)
data$country <- ifelse(data$cowcode == 817 , 'Republic of Vietnam' , data$country)
data$country <- ifelse(data$cowcode == 360 , 'Romania'  , data$country)
data$country <- ifelse(data$cowcode == 517 , 'Rwanda'  , data$country)
data$country <- ifelse(data$cowcode == 990 , 'Samoa'  , data$country)
data$country <- ifelse(data$cowcode == 331 , 'San Marino' , data$country)
data$country <- ifelse(data$cowcode == 403 , 'Sao Tome and Principe' , data$country)
data$country <- ifelse(data$cowcode == 670 , 'Saudi Arabia' , data$country)
data$country <- ifelse(data$cowcode == 269 , 'Saxony' , data$country)
data$country <- ifelse(data$cowcode == 433 , 'Senegal'  , data$country)
data$country <- ifelse(data$cowcode == 591 , 'Seychelles'  , data$country)
data$country <- ifelse(data$cowcode == 451 , 'Sierra Leone'  , data$country)
data$country <- ifelse(data$cowcode == 830 , 'Singapore'  , data$country)
data$country <- ifelse(data$cowcode == 317 , 'Slovakia'  , data$country)
data$country <- ifelse(data$cowcode == 349 , 'Slovenia'  , data$country)
data$country <- ifelse(data$cowcode == 940 , 'Solomon Islands'  , data$country)
data$country <- ifelse(data$cowcode == 520 , 'Somalia'  , data$country)
data$country <- ifelse(data$cowcode == 560 , 'South Africa'  , data$country)
data$country <- ifelse(data$cowcode == 732 , 'Korea, South' , data$country)
data$country <- ifelse(data$cowcode == 230 , 'Spain'  , data$country)
data$country <- ifelse(data$cowcode == 780 , 'Sri Lanka'  , data$country)
data$country <- ifelse(data$cowcode == 60 , 'St. Kitts and Nevis'  , data$country)
data$country <- ifelse(data$cowcode == 56 , 'St. Lucia'  , data$country)
data$country <- ifelse(data$cowcode == 57 , 'St. Vincent and the Grenadines' , data$country)
data$country <- ifelse(data$cowcode == 625 , 'Sudan'  , data$country)
data$country <- ifelse(data$cowcode == 115 , 'Suriname'  , data$country)
data$country <- ifelse(data$cowcode == 572 , 'Swaziland'  , data$country)
data$country <- ifelse(data$cowcode == 380 , 'Sweden'  , data$country)
data$country <- ifelse(data$cowcode == 225 , 'Switzerland'  , data$country)
data$country <- ifelse(data$cowcode == 652 , 'Syrian Arab Republic' , data$country)
data$country <- ifelse(data$cowcode == 713 , 'Taiwan' , data$country)
data$country <- ifelse(data$cowcode == 702 , 'Tajikistan'  , data$country)
data$country <- ifelse(data$cowcode == 510 , 'Tanzania'  , data$country)
data$country <- ifelse(data$cowcode == 800 , 'Thailand'  , data$country)
data$country <- ifelse(data$cowcode == 461 , 'Togo'  , data$country)
data$country <- ifelse(data$cowcode == 955 , 'Tonga' , data$country)
data$country <- ifelse(data$cowcode == 52 , 'Trinidad and Tobago'  , data$country)
data$country <- ifelse(data$cowcode == 616 , 'Tunisia'  , data$country)
data$country <- ifelse(data$cowcode == 640 , 'Turkey'  , data$country)
data$country <- ifelse(data$cowcode == 701 , 'Turkmenistan' , data$country)
data$country <- ifelse(data$cowcode == 337 , 'Tuscany' , data$country)
data$country <- ifelse(data$cowcode == 947 , 'Tuvalu' , data$country)
data$country <- ifelse(data$cowcode == 329 , 'Two Sicilies' , data$country)
data$country <- ifelse(data$cowcode == 365 , 'Russian Federation' , data$country)
data$country <- ifelse(data$cowcode == 500 , 'Uganda'  , data$country)
data$country <- ifelse(data$cowcode == 369 , 'Ukraine' , data$country)
data$country <- ifelse(data$cowcode == 696 , 'United Arab Emirates'  , data$country)
data$country <- ifelse(data$cowcode == 200 , 'United Kingdom'  , data$country)
data$country <- ifelse(data$cowcode == 2 , 'United States' , data$country)
data$country <- ifelse(data$cowcode == 165 , 'Uruguay'  , data$country)
data$country <- ifelse(data$cowcode == 704 , 'Uzbekistan' , data$country)
data$country <- ifelse(data$cowcode == 935 , 'Vanuatu'  , data$country)
data$country <- ifelse(data$cowcode == 101 , 'Venezuela' , data$country)
data$country <- ifelse(data$cowcode == 816 , 'Vietnam' , data$country)
data$country <- ifelse(data$cowcode == 271 , 'Wuerttemburg' , data$country)
data$country <- ifelse(data$cowcode == 678 , 'Yemen Arab Republic' , data$country)
data$country <- ifelse(data$cowcode == 679 , 'Yemen' , data$country)
data$country <- ifelse(data$cowcode == 680 , 'Yemen People\'s Republic'  , data$country)
data$country <- ifelse(data$cowcode == 345 , 'Yugoslavia / Serbia & Montenegro' , data$country)
data$country <- ifelse(data$cowcode == 490 , 'Zaire / Dem. Rep. Congo' , data$country)
data$country <- ifelse(data$cowcode == 551 , 'Zambia'  , data$country)
data$country <- ifelse(data$cowcode == 511 , 'Zanzibar' , data$country)
data$country <- ifelse(data$cowcode == 552 , 'Zimbabwe'  , data$country)
data$country <- ifelse(data$cowcode == 715 , 'Hong Kong, SAR' , data$country)
data$country <- ifelse(data$cowcode == 716 , 'Macao, SAR' , data$country)

#WDI countries      data$country)
data$country <- ifelse(data$cowcode == 1001 , 'American Samoa' , data$country)
data$country <- ifelse(data$cowcode == 1002 , 'Aruba' , data$country)
data$country <- ifelse(data$cowcode == 1003 , 'Bermuda' , data$country)
data$country <- ifelse(data$cowcode == 1004 , 'Cayman Islands' , data$country)
data$country <- ifelse(data$cowcode == 1005 , 'Channel Islands' , data$country)
data$country <- ifelse(data$cowcode == 1006 , 'Curacao' , data$country)
data$country <- ifelse(data$cowcode == 1007 , 'Faeroe Islands' , data$country)
data$country <- ifelse(data$cowcode == 1008 , 'French Polynesia' , data$country)
data$country <- ifelse(data$cowcode == 1009 , 'Greenland' , data$country)
data$country <- ifelse(data$cowcode == 1010 , 'Guam' , data$country)
data$country <- ifelse(data$cowcode == 1011 , 'Isle of Man' , data$country)
data$country <- ifelse(data$cowcode == 1012 , 'New Caledonia' , data$country)
data$country <- ifelse(data$cowcode == 1013 , 'Northern Mariana Islands' , data$country)
data$country <- ifelse(data$cowcode == 1014 , 'Puerto Rico' , data$country)
data$country <- ifelse(data$cowcode == 1015 , 'Serbia' , data$country)
data$country <- ifelse(data$cowcode == 1016 , 'Sint Maarten (Dutch part)' , data$country)
data$country <- ifelse(data$cowcode == 1017 , 'St. Martin (French part)' , data$country)
data$country <- ifelse(data$cowcode == 1018 , 'Turks and Caicos Islands' , data$country)
data$country <- ifelse(data$cowcode == 1019 , 'Virgin Islands (U.S.)' , data$country)
data$country <- ifelse(data$cowcode == 1020 , 'West Bank and Gaza'  , data$country)
data$country <- ifelse(data$cowcode == 1021 , 'South Sudan' , data$country)

#WDI geographic areas      data$country)
data$country <- ifelse(data$cowcode == 2010 , 'East Asia & Pacific (all income levels)' , data$country)
data$country <- ifelse(data$cowcode == 2011 , 'East Asia & Pacific (developing only)' , data$country)
data$country <- ifelse(data$cowcode == 2012 , 'East Asia and the Pacific (IFC classification)' , data$country)
data$country <- ifelse(data$cowcode == 2020 , 'Europe & Central Asia (all income levels)' , data$country)
data$country <- ifelse(data$cowcode == 2021 , 'Europe & Central Asia (developing only)' , data$country)
data$country <- ifelse(data$cowcode == 2022 , 'Europe and Central Asia (IFC classification)' , data$country)
data$country <- ifelse(data$cowcode == 2030 , 'Latin America & Caribbean (all income levels)' , data$country)
data$country <- ifelse(data$cowcode == 2031 , 'Latin America & Caribbean (developing only)' , data$country)
data$country <- ifelse(data$cowcode == 2032 , 'Latin America and the Caribbean (IFC classification)' , data$country)
data$country <- ifelse(data$cowcode == 2040 , 'Middle East & North Africa (all income levels)' , data$country)
data$country <- ifelse(data$cowcode == 2041 , 'Middle East & North Africa (developing only)' , data$country)
data$country <- ifelse(data$cowcode == 2042 , 'Middle East and North Africa (IFC classification)' , data$country)
data$country <- ifelse(data$cowcode == 2050 , 'Sub-Saharan Africa (all income levels)' , data$country)
data$country <- ifelse(data$cowcode == 2051 , 'Sub-Saharan Africa (developing only)' , data$country)
data$country <- ifelse(data$cowcode == 2052 , 'Sub-Saharan Africa (IFC classification)' , data$country)
data$country <- ifelse(data$cowcode == 2060 , 'North America' , data$country)
data$country <- ifelse(data$cowcode == 2070 , 'European Union' , data$country)
data$country <- ifelse(data$cowcode == 2071 , 'Euro area' , data$country)
data$country <- ifelse(data$cowcode == 2072 , 'OECD members' , data$country)
data$country <- ifelse(data$cowcode == 2080 , 'Arab World' , data$country)
data$country <- ifelse(data$cowcode == 2085 , 'South Asia' , data$country)
data$country <- ifelse(data$cowcode == 2086 , 'South Asia (IFC classification)' , data$country)
data$country <- ifelse(data$cowcode == 2090 , 'Small states' , data$country)
data$country <- ifelse(data$cowcode == 2091 , 'Pacific island small states' , data$country)
data$country <- ifelse(data$cowcode == 2092 , 'Caribbean small states' , data$country)
data$country <- ifelse(data$cowcode == 2093 , 'Other small states' , data$country)
data$country <- ifelse(data$cowcode == 2099 , 'World' , data$country)
data$country <- ifelse(data$cowcode == 2100 , 'Not classified' , data$country)
     
     
#WDI income groups     
data$country <- ifelse(data$cowcode == 3001 , 'Heavily indebted poor countries (HIPC)' , data$country)
data$country <- ifelse(data$cowcode == 3002 , 'Least developed countries: UN classification' , data$country)
data$country <- ifelse(data$cowcode == 3003 , 'Low income' , data$country)
data$country <- ifelse(data$cowcode == 3004 , 'Lower middle income' , data$country)
data$country <- ifelse(data$cowcode == 3005 , 'Low & middle income' , data$country)
data$country <- ifelse(data$cowcode == 3006 , 'Middle income' , data$country)
data$country <- ifelse(data$cowcode == 3007 , 'Upper middle income' , data$country)
data$country <- ifelse(data$cowcode == 3008 , 'High income' , data$country)
data$country <- ifelse(data$cowcode == 3009 , 'High income: OECD' , data$country)
data$country <- ifelse(data$cowcode == 3010 , 'High income: nonOECD' , data$country)

#AMECO aggregates     
data$country <- ifelse(data$cowcode == 2101 , 'EA12 (12 countries)' , data$country)
data$country <- ifelse(data$cowcode == 2102 , 'EA12 (including D_W West-Germany)' , data$country)
data$country <- ifelse(data$cowcode == 2103 , 'EA17 (17 countries)' , data$country)
data$country <- ifelse(data$cowcode == 2104 , 'EU12 (12 New Member States)' , data$country)
data$country <- ifelse(data$cowcode == 2105 , 'EU15 (15 countries)' , data$country)
data$country <- ifelse(data$cowcode == 2106 , 'EU15 (including D_W West-Germany)' , data$country)
data$country <- ifelse(data$cowcode == 2107 , 'EU27 (27 countries)' , data$country)
data$country <- ifelse(data$cowcode == 2108 , 'Euro area (12 countries)' , data$country)
data$country <- ifelse(data$cowcode == 2109 , 'Euro area (17 countries)' , data$country)
data$country <- ifelse(data$cowcode == 2110 , 'European Union (15 countries)' , data$country)
data$country <- ifelse(data$cowcode == 2111 , 'European Union (27 countries)' , data$country)
data$country <- ifelse(data$cowcode == 2112 , 'European Union (28 countries)' , data$country)
     
#GSF additions     
data$country <- ifelse(data$cowcode == 1022 , 'Anguilla' , data$country)
data$country <- ifelse(data$cowcode == 1023 , 'Netherlands Antilles' , data$country)
     
#Barro * Lee additions     
data$country <- ifelse(data$cowcode == 1024 , 'Reunion'  , data$country)
     
#All the Ginis additions     
data$country <- ifelse(data$cowcode == 1025 , 'French Guiana' , data$country)
data$country <- ifelse(data$cowcode == 1026 , 'Guadeloupe' , data$country)

#Institute for Democracy And Electoral Assistance additions
data$cowcode <- ifelse(data$country == 1027,  'Cook Islands' , data$cowcode)
data$cowcode <- ifelse(data$country == 1028, 'Faroe Islands' , data$cowcode)
data$cowcode <- ifelse(data$country == 1029, 'Gibraltar' , data$cowcode)
data$cowcode <- ifelse(data$country == 1030, 'Montserrat' , data$cowcode)
data$cowcode <- ifelse(data$country == 1031, 'Virgin Islands, British' , data$cowcode)

#*Banking Regulations and Supervision additions
data$cowcode <- ifelse(data$country == 1032, 'Jersey' , data$cowcode)
data$cowcode <- ifelse(data$country == 1033, 'Guernsey' , data$cowcode)

return(data)
}

